# Docker 网络访问说明：
# 服务间通信： 使用服务名 postgres (不是 localhost)
# 内部端口： 使用 5432 (不是映射端口 15432)
# 外部访问： 从宿主机可以通过 localhost:15432 访问数据库
# 应用访问： 从宿主机可以通过 localhost:38000 访问应用

services:
  # Nginx Proxy Manager - SSL 代理和证书管理
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: finance_nginx
    ports:
      # - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # 管理界面
    environment:
      - DB_MYSQL_HOST=nginx-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm_password
      - DB_MYSQL_NAME=npm
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - finance_network
    depends_on:
      - nginx-db
    restart: unless-stopped

  # Nginx Proxy Manager 数据库
  nginx-db:
    image: mysql:5.7
    container_name: finance_nginx_db
    expose:
      - "3306"  # 仅在内部网络暴露
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm_password
    volumes:
      - nginx_db_data:/var/lib/mysql
    networks:
      - finance_network
    restart: unless-stopped

  # 数据库
  postgres:
    image: postgres:16-alpine
    container_name: finance_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=anyu
      - POSTGRES_PASSWORD=zvRdM7SGj1ZewKhtCGLngY4hgkXUO5y9
      - POSTGRES_DB=finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anyu -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  # 应用服务
  app:
    build: .
    platform: linux/amd64  # 指定架构：linux/amd64 或 linux/arm64，跨平台时注意替换
    # ports:
    #   - "38000:8000"  # 通过nginx代理访问，不需要直接暴露端口
    expose:
      - "8000"  # 仅在内部网络暴露
    environment:
      # 数据库连接配置
      DATABASE_URL: postgresql+asyncpg://anyu:zvRdM7SGj1ZewKhtCGLngY4hgkXUO5y9@postgres:5432/finance_db
      
      # JWT配置
      JWT_SECRET_KEY: bb0b141a2c4f5ff013941a0971c5af1416b47ff2f6be21670cf223285322fe74
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      
      # 应用配置
      APP_NAME: 财务管理系统
      DEBUG: "false"
      API_V1_PREFIX: /api/v1
      
      # 邮件配置（Docker环境暂时使用占位符）
      MAIL_USERNAME: placeholder@example.com
      MAIL_PASSWORD: placeholder_password
      MAIL_FROM: noreply@example.com
      MAIL_PORT: 587
      MAIL_SERVER: smtp.example.com
      MAIL_TLS: "true"
      MAIL_SSL: "false"
      
      # 日志配置
      LOG_LEVEL: INFO
      LOG_DIR: logs
      
      # 超级管理员配置
      FIRST_SUPERUSER_EMAIL: 1308340194@qq.com
      FIRST_SUPERUSER_PASSWORD: admin123
      FIRST_SUPERUSER_FULL_NAME: 系统管理员
      FIRST_SUPERUSER_PHONE: "13246834775"
    networks:
      - finance_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped 

volumes:
  postgres_data:
    name: finance_postgres_data
  nginx_data:
    name: finance_nginx_data
  nginx_db_data:
    name: finance_nginx_db_data
  nginx_letsencrypt:
    name: finance_nginx_letsencrypt

networks:
  finance_network:
    name: finance_network 