services:
  postgres:
    image: postgres:16-alpine
    container_name: finance_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=anyu
      - POSTGRES_PASSWORD=zvRdM7SGj1ZewKhtCGLngY4hgkXUO5y9
      - POSTGRES_DB=finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anyu -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: finance_postgres_data

networks:
  finance_network:
    name: finance_network 