[project]
name = "finance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.15.1",
    "fastapi>=0.115.11",
    "passlib>=1.7.4",
    "python-jose>=3.4.0",
    "sqlalchemy>=2.0.38",
]
