"""Update sales record fields for USD orders

Revision ID: 0fa1ad4e45b2
Revises: 155f145d378f
Create Date: 2025-06-02 23:08:04.678299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fa1ad4e45b2'
down_revision: Union[str, None] = '155f145d378f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salesrecord', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('salesrecord', sa.Column('total_price', sa.Float(precision=2), nullable=False))
    op.add_column('salesrecord', sa.Column('domestic_shipping_fee', sa.Float(precision=2), nullable=False))
    op.add_column('salesrecord', sa.Column('overseas_shipping_fee', sa.Float(precision=2), nullable=False))
    op.add_column('salesrecord', sa.Column('logistics_company', sa.String(length=100), nullable=True))
    op.add_column('salesrecord', sa.Column('profit', sa.Float(precision=2), nullable=False))
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('salesrecord', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('salesrecord', 'shipping_fee')
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('salesrecord', sa.Column('shipping_fee', sa.REAL(), autoincrement=False, nullable=False))
    op.alter_column('salesrecord', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('salesrecord', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('salesrecord', 'profit')
    op.drop_column('salesrecord', 'logistics_company')
    op.drop_column('salesrecord', 'overseas_shipping_fee')
    op.drop_column('salesrecord', 'domestic_shipping_fee')
    op.drop_column('salesrecord', 'total_price')
    op.drop_column('salesrecord', 'category')
    # ### end Alembic commands ###
