"""remove_category_from_sales_record

Revision ID: 4b84ae9f6384
Revises: 8f14dc08b71c
Create Date: 2025-07-11 10:34:52.329562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b84ae9f6384'
down_revision: Union[str, None] = '8f14dc08b71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procurement', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'factory_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_column('salesrecord', 'category')
    op.alter_column('shippingfees', 'shipping_fee',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shippingfees', 'shipping_fee',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('salesrecord', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'factory_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('procurement', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
