"""add_is_voided_field_to_sales_shipping_procurement

Revision ID: bf783d55aca5
Revises: 266739d93b46
Create Date: 2025-08-05 17:33:24.081103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf783d55aca5'
down_revision: Union[str, None] = '266739d93b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement', sa.Column('is_voided', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('procurement', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('salesrecord', sa.Column('is_voided', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'factory_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('shippingfees', sa.Column('is_voided', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('shippingfees', 'shipping_fee',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shippingfees', 'shipping_fee',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('shippingfees', 'is_voided')
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'factory_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('salesrecord', 'is_voided')
    op.alter_column('procurement', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('procurement', 'is_voided')
    # ### end Alembic commands ###
