"""Add shipping fees and procurement tables

Revision ID: caee636c8781
Revises: 02da9ac70ab0
Create Date: 2025-07-08 17:29:01.125717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caee636c8781'
down_revision: Union[str, None] = '02da9ac70ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_record_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('procurement_item', sa.String(length=1000), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sales_record_id'], ['salesrecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_id'), 'procurement', ['id'], unique=False)
    op.create_table('shippingfees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_record_id', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', sa.Float(precision=2), nullable=False),
    sa.Column('logistics_type', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('logistics_company', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sales_record_id'], ['salesrecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippingfees_id'), 'shippingfees', ['id'], unique=False)
    op.add_column('salesrecord', sa.Column('order_source', sa.String(length=20), nullable=False))
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_column('salesrecord', 'domestic_shipping_fee')
    op.drop_column('salesrecord', 'logistics_company')
    op.drop_column('salesrecord', 'overseas_shipping_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salesrecord', sa.Column('overseas_shipping_fee', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('salesrecord', sa.Column('logistics_company', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('salesrecord', sa.Column('domestic_shipping_fee', sa.REAL(), autoincrement=False, nullable=False))
    op.alter_column('salesrecord', 'profit',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'tax_refund',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'refund_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'exchange_rate',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'7'::real"))
    op.alter_column('salesrecord', 'total_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('salesrecord', 'unit_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('salesrecord', 'order_source')
    op.drop_index(op.f('ix_shippingfees_id'), table_name='shippingfees')
    op.drop_table('shippingfees')
    op.drop_index(op.f('ix_procurement_id'), table_name='procurement')
    op.drop_table('procurement')
    # ### end Alembic commands ###
